// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_SUBPROCESS_HOST_H
#define __BINDINGS_SUBPROCESS_HOST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct subprocess_host_string_t {
  uint8_t*ptr;
  size_t len;
} subprocess_host_string_t;

typedef struct io_error_own_error_t {
  int32_t __handle;
} io_error_own_error_t;

typedef struct io_error_borrow_error_t {
  int32_t __handle;
} io_error_borrow_error_t;

typedef struct poll_own_pollable_t {
  int32_t __handle;
} poll_own_pollable_t;

typedef struct poll_borrow_pollable_t {
  int32_t __handle;
} poll_borrow_pollable_t;

typedef struct {
  poll_borrow_pollable_t *ptr;
  size_t len;
} poll_list_borrow_pollable_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} subprocess_host_list_u32_t;

typedef io_error_own_error_t streams_own_error_t;

// An error for input-stream and output-stream operations.
typedef struct streams_stream_error_t {
  uint8_t tag;
  union {
    streams_own_error_t     last_operation_failed;
  } val;
} streams_stream_error_t;

// The last operation (a write or flush) failed before completion.
// 
// More information is available in the `error` payload.
#define STREAMS_STREAM_ERROR_LAST_OPERATION_FAILED 0
// The stream is closed: no more input will be accepted by the
// stream. A closed output-stream will return this error on all
// future operations.
#define STREAMS_STREAM_ERROR_CLOSED 1

typedef struct streams_own_input_stream_t {
  int32_t __handle;
} streams_own_input_stream_t;

typedef struct streams_borrow_input_stream_t {
  int32_t __handle;
} streams_borrow_input_stream_t;

typedef struct streams_own_output_stream_t {
  int32_t __handle;
} streams_own_output_stream_t;

typedef struct streams_borrow_output_stream_t {
  int32_t __handle;
} streams_borrow_output_stream_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} subprocess_host_list_u8_t;

typedef struct {
  bool is_err;
  union {
    subprocess_host_list_u8_t ok;
    streams_stream_error_t err;
  } val;
} streams_result_list_u8_stream_error_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    streams_stream_error_t err;
  } val;
} streams_result_u64_stream_error_t;

typedef poll_own_pollable_t streams_own_pollable_t;

typedef struct {
  bool is_err;
  union {
    streams_stream_error_t err;
  } val;
} streams_result_void_stream_error_t;

typedef streams_own_input_stream_t devenv_subprocess_types_own_input_stream_t;

typedef struct devenv_subprocess_types_stdin_t {
  uint8_t tag;
  union {
    devenv_subprocess_types_own_input_stream_t     pipe;
  } val;
} devenv_subprocess_types_stdin_t;

// Inherit the platform-defined stdin for this subprocess.
#define DEVENV_SUBPROCESS_TYPES_STDIN_INHERIT 0
// Provide a closed stdin. Reads observe EOF.
#define DEVENV_SUBPROCESS_TYPES_STDIN_CLOSED 1
// Provide this stream as the child's stdin.
#define DEVENV_SUBPROCESS_TYPES_STDIN_PIPE 2

typedef struct devenv_subprocess_types_output_t {
  uint8_t tag;
} devenv_subprocess_types_output_t;

// Inherit the platform-defined output stream for this subprocess.
#define DEVENV_SUBPROCESS_TYPES_OUTPUT_INHERIT 0
// Discard output.
#define DEVENV_SUBPROCESS_TYPES_OUTPUT_DISCARD 1
// Pipe output back to the parent. The stream is available from the child
// resource method.
#define DEVENV_SUBPROCESS_TYPES_OUTPUT_PIPE 2

typedef struct {
  subprocess_host_string_t *ptr;
  size_t len;
} subprocess_host_list_string_t;

typedef struct {
  bool is_some;
  subprocess_host_string_t val;
} subprocess_host_option_string_t;

typedef struct {
  subprocess_host_string_t f0;
  subprocess_host_string_t f1;
} subprocess_host_tuple2_string_string_t;

typedef struct {
  subprocess_host_tuple2_string_string_t *ptr;
  size_t len;
} subprocess_host_list_tuple2_string_string_t;

typedef struct {
  bool is_some;
  devenv_subprocess_types_stdin_t val;
} devenv_subprocess_types_option_stdin_t;

typedef struct {
  bool is_some;
  devenv_subprocess_types_output_t val;
} devenv_subprocess_types_option_output_t;

typedef struct devenv_subprocess_types_spawn_options_t {
  // Host-resolved command name or path.
  subprocess_host_string_t   command;
  // Full WASI CLI argument list for the child, including argv[0].
  subprocess_host_list_string_t   arguments;
  // Working directory in the child's filesystem namespace.
  subprocess_host_option_string_t   cwd;
  // Environment additions/overrides applied to the platform-inherited child
  // environment.
  subprocess_host_list_tuple2_string_string_t   environment;
  // Defaults to inherit when absent.
  devenv_subprocess_types_option_stdin_t   stdin_;
  // Defaults to inherit when absent.
  devenv_subprocess_types_option_output_t   stdout_;
  // Defaults to inherit when absent.
  devenv_subprocess_types_option_output_t   stderr_;
} devenv_subprocess_types_spawn_options_t;

typedef struct {
  bool is_err;
} devenv_subprocess_types_result_void_void_t;

typedef struct devenv_subprocess_types_exit_status_t {
  uint8_t tag;
  union {
    devenv_subprocess_types_result_void_void_t     exited;
    uint8_t     exited_with_code;
  } val;
} devenv_subprocess_types_exit_status_t;

// Child exited with the stable WASI success/failure result.
#define DEVENV_SUBPROCESS_TYPES_EXIT_STATUS_EXITED 0
// Child used WASI exit-with-code.
#define DEVENV_SUBPROCESS_TYPES_EXIT_STATUS_EXITED_WITH_CODE 1
// Child was terminated by the host or parent.
#define DEVENV_SUBPROCESS_TYPES_EXIT_STATUS_TERMINATED 2

typedef struct devenv_subprocess_types_own_child_t {
  int32_t __handle;
} devenv_subprocess_types_own_child_t;

typedef struct devenv_subprocess_types_borrow_child_t {
  int32_t __handle;
} devenv_subprocess_types_borrow_child_t;

typedef struct {
  bool is_some;
  devenv_subprocess_types_own_input_stream_t val;
} devenv_subprocess_types_option_own_input_stream_t;

typedef poll_own_pollable_t devenv_subprocess_types_own_pollable_t;

typedef struct {
  bool is_some;
  devenv_subprocess_types_exit_status_t val;
} devenv_subprocess_types_option_exit_status_t;

typedef devenv_subprocess_types_spawn_options_t devenv_subprocess_host_spawn_options_t;

typedef devenv_subprocess_types_own_child_t devenv_subprocess_host_own_child_t;

typedef struct {
  bool is_err;
  union {
    devenv_subprocess_host_own_child_t ok;
    subprocess_host_string_t err;
  } val;
} devenv_subprocess_host_result_own_child_string_t;

// Imported Functions from `wasi:io/error@0.2.0`
// Returns a string that is suitable to assist humans in debugging
// this error.
// 
// WARNING: The returned string should not be consumed mechanically!
// It may change across platforms, hosts, or other implementation
// details. Parsing this string is a major platform-compatibility
// hazard.
extern void io_error_method_error_to_debug_string(io_error_borrow_error_t self, subprocess_host_string_t *ret);

// Imported Functions from `wasi:io/poll@0.2.0`
// Return the readiness of a pollable. This function never blocks.
// 
// Returns `true` when the pollable is ready, and `false` otherwise.
extern bool poll_method_pollable_ready(poll_borrow_pollable_t self);
// `block` returns immediately if the pollable is ready, and otherwise
// blocks until ready.
// 
// This function is equivalent to calling `poll.poll` on a list
// containing only this pollable.
extern void poll_method_pollable_block(poll_borrow_pollable_t self);
// Poll for completion on a set of pollables.
// 
// This function takes a list of pollables, which identify I/O sources of
// interest, and waits until one or more of the events is ready for I/O.
// 
// The result `list<u32>` contains one or more indices of handles in the
// argument list that is ready for I/O.
// 
// If the list contains more elements than can be indexed with a `u32`
// value, this function traps.
// 
// A timeout can be implemented by adding a pollable from the
// wasi-clocks API to the list.
// 
// This function does not return a `result`; polling in itself does not
// do any I/O so it doesn't fail. If any of the I/O sources identified by
// the pollables has an error, it is indicated by marking the source as
// being reaedy for I/O.
extern void poll_poll(poll_list_borrow_pollable_t *in, subprocess_host_list_u32_t *ret);

// Imported Functions from `wasi:io/streams@0.2.0`
// Perform a non-blocking read from the stream.
// 
// When the source of a `read` is binary data, the bytes from the source
// are returned verbatim. When the source of a `read` is known to the
// implementation to be text, bytes containing the UTF-8 encoding of the
// text are returned.
// 
// This function returns a list of bytes containing the read data,
// when successful. The returned list will contain up to `len` bytes;
// it may return fewer than requested, but not more. The list is
// empty when no bytes are available for reading at this time. The
// pollable given by `subscribe` will be ready when more bytes are
// available.
// 
// This function fails with a `stream-error` when the operation
// encounters an error, giving `last-operation-failed`, or when the
// stream is closed, giving `closed`.
// 
// When the caller gives a `len` of 0, it represents a request to
// read 0 bytes. If the stream is still open, this call should
// succeed and return an empty list, or otherwise fail with `closed`.
// 
// The `len` parameter is a `u64`, which could represent a list of u8 which
// is not possible to allocate in wasm32, or not desirable to allocate as
// as a return value by the callee. The callee may return a list of bytes
// less than `len` in size while more bytes are available for reading.
extern bool streams_method_input_stream_read(streams_borrow_input_stream_t self, uint64_t len, subprocess_host_list_u8_t *ret, streams_stream_error_t *err);
// Read bytes from a stream, after blocking until at least one byte can
// be read. Except for blocking, behavior is identical to `read`.
extern bool streams_method_input_stream_blocking_read(streams_borrow_input_stream_t self, uint64_t len, subprocess_host_list_u8_t *ret, streams_stream_error_t *err);
// Skip bytes from a stream. Returns number of bytes skipped.
// 
// Behaves identical to `read`, except instead of returning a list
// of bytes, returns the number of bytes consumed from the stream.
extern bool streams_method_input_stream_skip(streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, streams_stream_error_t *err);
// Skip bytes from a stream, after blocking until at least one byte
// can be skipped. Except for blocking behavior, identical to `skip`.
extern bool streams_method_input_stream_blocking_skip(streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, streams_stream_error_t *err);
// Create a `pollable` which will resolve once either the specified stream
// has bytes available to read or the other end of the stream has been
// closed.
// The created `pollable` is a child resource of the `input-stream`.
// Implementations may trap if the `input-stream` is dropped before
// all derived `pollable`s created with this function are dropped.
extern streams_own_pollable_t streams_method_input_stream_subscribe(streams_borrow_input_stream_t self);
// Check readiness for writing. This function never blocks.
// 
// Returns the number of bytes permitted for the next call to `write`,
// or an error. Calling `write` with more bytes than this function has
// permitted will trap.
// 
// When this function returns 0 bytes, the `subscribe` pollable will
// become ready when this function will report at least 1 byte, or an
// error.
extern bool streams_method_output_stream_check_write(streams_borrow_output_stream_t self, uint64_t *ret, streams_stream_error_t *err);
// Perform a write. This function never blocks.
// 
// When the destination of a `write` is binary data, the bytes from
// `contents` are written verbatim. When the destination of a `write` is
// known to the implementation to be text, the bytes of `contents` are
// transcoded from UTF-8 into the encoding of the destination and then
// written.
// 
// Precondition: check-write gave permit of Ok(n) and contents has a
// length of less than or equal to n. Otherwise, this function will trap.
// 
// returns Err(closed) without writing if the stream has closed since
// the last call to check-write provided a permit.
extern bool streams_method_output_stream_write(streams_borrow_output_stream_t self, subprocess_host_list_u8_t *contents, streams_stream_error_t *err);
// Perform a write of up to 4096 bytes, and then flush the stream. Block
// until all of these operations are complete, or an error occurs.
// 
// This is a convenience wrapper around the use of `check-write`,
// `subscribe`, `write`, and `flush`, and is implemented with the
// following pseudo-code:
// 
// ```text
// let pollable = this.subscribe();
// while !contents.is_empty() {
// // Wait for the stream to become writable
// pollable.block();
// let Ok(n) = this.check-write(); // eliding error handling
// let len = min(n, contents.len());
// let (chunk, rest) = contents.split_at(len);
// this.write(chunk  );            // eliding error handling
// contents = rest;
// }
// this.flush();
// // Wait for completion of `flush`
// pollable.block();
// // Check for any errors that arose during `flush`
// let _ = this.check-write();         // eliding error handling
// ```
extern bool streams_method_output_stream_blocking_write_and_flush(streams_borrow_output_stream_t self, subprocess_host_list_u8_t *contents, streams_stream_error_t *err);
// Request to flush buffered output. This function never blocks.
// 
// This tells the output-stream that the caller intends any buffered
// output to be flushed. the output which is expected to be flushed
// is all that has been passed to `write` prior to this call.
// 
// Upon calling this function, the `output-stream` will not accept any
// writes (`check-write` will return `ok(0)`) until the flush has
// completed. The `subscribe` pollable will become ready when the
// flush has completed and the stream can accept more writes.
extern bool streams_method_output_stream_flush(streams_borrow_output_stream_t self, streams_stream_error_t *err);
// Request to flush buffered output, and block until flush completes
// and stream is ready for writing again.
extern bool streams_method_output_stream_blocking_flush(streams_borrow_output_stream_t self, streams_stream_error_t *err);
// Create a `pollable` which will resolve once the output-stream
// is ready for more writing, or an error has occured. When this
// pollable is ready, `check-write` will return `ok(n)` with n>0, or an
// error.
// 
// If the stream is closed, this pollable is always ready immediately.
// 
// The created `pollable` is a child resource of the `output-stream`.
// Implementations may trap if the `output-stream` is dropped before
// all derived `pollable`s created with this function are dropped.
extern streams_own_pollable_t streams_method_output_stream_subscribe(streams_borrow_output_stream_t self);
// Write zeroes to a stream.
// 
// This should be used precisely like `write` with the exact same
// preconditions (must use check-write first), but instead of
// passing a list of bytes, you simply pass the number of zero-bytes
// that should be written.
extern bool streams_method_output_stream_write_zeroes(streams_borrow_output_stream_t self, uint64_t len, streams_stream_error_t *err);
// Perform a write of up to 4096 zeroes, and then flush the stream.
// Block until all of these operations are complete, or an error
// occurs.
// 
// This is a convenience wrapper around the use of `check-write`,
// `subscribe`, `write-zeroes`, and `flush`, and is implemented with
// the following pseudo-code:
// 
// ```text
// let pollable = this.subscribe();
// while num_zeroes != 0 {
// // Wait for the stream to become writable
// pollable.block();
// let Ok(n) = this.check-write(); // eliding error handling
// let len = min(n, num_zeroes);
// this.write-zeroes(len);         // eliding error handling
// num_zeroes -= len;
// }
// this.flush();
// // Wait for completion of `flush`
// pollable.block();
// // Check for any errors that arose during `flush`
// let _ = this.check-write();         // eliding error handling
// ```
extern bool streams_method_output_stream_blocking_write_zeroes_and_flush(streams_borrow_output_stream_t self, uint64_t len, streams_stream_error_t *err);
// Read from one stream and write to another.
// 
// The behavior of splice is equivelant to:
// 1. calling `check-write` on the `output-stream`
// 2. calling `read` on the `input-stream` with the smaller of the
// `check-write` permitted length and the `len` provided to `splice`
// 3. calling `write` on the `output-stream` with that read data.
// 
// Any error reported by the call to `check-write`, `read`, or
// `write` ends the splice and reports that error.
// 
// This function returns the number of bytes transferred; it may be less
// than `len`.
extern bool streams_method_output_stream_splice(streams_borrow_output_stream_t self, streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, streams_stream_error_t *err);
// Read from one stream and write to another, with blocking.
// 
// This is similar to `splice`, except that it blocks until the
// `output-stream` is ready for writing, and the `input-stream`
// is ready for reading, before performing the `splice`.
extern bool streams_method_output_stream_blocking_splice(streams_borrow_output_stream_t self, streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, streams_stream_error_t *err);

// Imported Functions from `devenv:subprocess/types@0.2.0-draft`
// Return the child's stdout stream when stdout was configured as pipe.
extern bool devenv_subprocess_types_method_child_stdout(devenv_subprocess_types_borrow_child_t self, devenv_subprocess_types_own_input_stream_t *ret);
// Return the child's stderr stream when stderr was configured as pipe.
extern bool devenv_subprocess_types_method_child_stderr(devenv_subprocess_types_borrow_child_t self, devenv_subprocess_types_own_input_stream_t *ret);
// Subscribe to child completion.
extern devenv_subprocess_types_own_pollable_t devenv_subprocess_types_method_child_subscribe(devenv_subprocess_types_borrow_child_t self);
// Return the exit status if the child has exited.
extern bool devenv_subprocess_types_method_child_exit_status(devenv_subprocess_types_borrow_child_t self, devenv_subprocess_types_exit_status_t *ret);
// Request best-effort child termination.
extern void devenv_subprocess_types_method_child_terminate(devenv_subprocess_types_borrow_child_t self);

// Imported Functions from `devenv:subprocess/host@0.2.0-draft`
// Spawn a child using host-defined resolution and policy.
extern bool devenv_subprocess_host_spawn(devenv_subprocess_host_spawn_options_t *options, devenv_subprocess_host_own_child_t *ret, subprocess_host_string_t *err);

// Helper Functions

extern void io_error_error_drop_own(io_error_own_error_t handle);

extern io_error_borrow_error_t io_error_borrow_error(io_error_own_error_t handle);

extern void poll_pollable_drop_own(poll_own_pollable_t handle);

extern poll_borrow_pollable_t poll_borrow_pollable(poll_own_pollable_t handle);

void poll_list_borrow_pollable_free(poll_list_borrow_pollable_t *ptr);

void subprocess_host_list_u32_free(subprocess_host_list_u32_t *ptr);

void streams_stream_error_free(streams_stream_error_t *ptr);

extern void streams_input_stream_drop_own(streams_own_input_stream_t handle);

extern streams_borrow_input_stream_t streams_borrow_input_stream(streams_own_input_stream_t handle);

extern void streams_output_stream_drop_own(streams_own_output_stream_t handle);

extern streams_borrow_output_stream_t streams_borrow_output_stream(streams_own_output_stream_t handle);

void subprocess_host_list_u8_free(subprocess_host_list_u8_t *ptr);

void streams_result_list_u8_stream_error_free(streams_result_list_u8_stream_error_t *ptr);

void streams_result_u64_stream_error_free(streams_result_u64_stream_error_t *ptr);

void streams_result_void_stream_error_free(streams_result_void_stream_error_t *ptr);

void devenv_subprocess_types_stdin_free(devenv_subprocess_types_stdin_t *ptr);

void devenv_subprocess_types_output_free(devenv_subprocess_types_output_t *ptr);

void subprocess_host_list_string_free(subprocess_host_list_string_t *ptr);

void subprocess_host_option_string_free(subprocess_host_option_string_t *ptr);

void subprocess_host_tuple2_string_string_free(subprocess_host_tuple2_string_string_t *ptr);

void subprocess_host_list_tuple2_string_string_free(subprocess_host_list_tuple2_string_string_t *ptr);

void devenv_subprocess_types_option_stdin_free(devenv_subprocess_types_option_stdin_t *ptr);

void devenv_subprocess_types_option_output_free(devenv_subprocess_types_option_output_t *ptr);

void devenv_subprocess_types_spawn_options_free(devenv_subprocess_types_spawn_options_t *ptr);

void devenv_subprocess_types_result_void_void_free(devenv_subprocess_types_result_void_void_t *ptr);

void devenv_subprocess_types_exit_status_free(devenv_subprocess_types_exit_status_t *ptr);

extern void devenv_subprocess_types_child_drop_own(devenv_subprocess_types_own_child_t handle);

extern devenv_subprocess_types_borrow_child_t devenv_subprocess_types_borrow_child(devenv_subprocess_types_own_child_t handle);

void devenv_subprocess_types_option_own_input_stream_free(devenv_subprocess_types_option_own_input_stream_t *ptr);

void devenv_subprocess_types_option_exit_status_free(devenv_subprocess_types_option_exit_status_t *ptr);

void devenv_subprocess_host_spawn_options_free(devenv_subprocess_host_spawn_options_t *ptr);

void devenv_subprocess_host_result_own_child_string_free(devenv_subprocess_host_result_own_child_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void subprocess_host_string_set(subprocess_host_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void subprocess_host_string_dup(subprocess_host_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void subprocess_host_string_dup_n(subprocess_host_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void subprocess_host_string_free(subprocess_host_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
