// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "subprocess_host.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wasi:io/error@0.2.0`

__attribute__((__import_module__("wasi:io/error@0.2.0"), __import_name__("[method]error.to-debug-string")))
extern void __wasm_import_io_error_method_error_to_debug_string(int32_t, uint8_t *);

// Imported Functions from `wasi:io/poll@0.2.0`

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("[method]pollable.ready")))
extern int32_t __wasm_import_poll_method_pollable_ready(int32_t);

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("[method]pollable.block")))
extern void __wasm_import_poll_method_pollable_block(int32_t);

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("poll")))
extern void __wasm_import_poll_poll(uint8_t *, size_t, uint8_t *);

// Imported Functions from `wasi:io/streams@0.2.0`

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.read")))
extern void __wasm_import_streams_method_input_stream_read(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.blocking-read")))
extern void __wasm_import_streams_method_input_stream_blocking_read(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.skip")))
extern void __wasm_import_streams_method_input_stream_skip(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.blocking-skip")))
extern void __wasm_import_streams_method_input_stream_blocking_skip(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.subscribe")))
extern int32_t __wasm_import_streams_method_input_stream_subscribe(int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.check-write")))
extern void __wasm_import_streams_method_output_stream_check_write(int32_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.write")))
extern void __wasm_import_streams_method_output_stream_write(int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-write-and-flush")))
extern void __wasm_import_streams_method_output_stream_blocking_write_and_flush(int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.flush")))
extern void __wasm_import_streams_method_output_stream_flush(int32_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-flush")))
extern void __wasm_import_streams_method_output_stream_blocking_flush(int32_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.subscribe")))
extern int32_t __wasm_import_streams_method_output_stream_subscribe(int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.write-zeroes")))
extern void __wasm_import_streams_method_output_stream_write_zeroes(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-write-zeroes-and-flush")))
extern void __wasm_import_streams_method_output_stream_blocking_write_zeroes_and_flush(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.splice")))
extern void __wasm_import_streams_method_output_stream_splice(int32_t, int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-splice")))
extern void __wasm_import_streams_method_output_stream_blocking_splice(int32_t, int32_t, int64_t, uint8_t *);

// Imported Functions from `devenv:subprocess/types@0.2.0-draft`

__attribute__((__import_module__("devenv:subprocess/types@0.2.0-draft"), __import_name__("[method]child.stdout")))
extern void __wasm_import_devenv_subprocess_types_method_child_stdout(int32_t, uint8_t *);

__attribute__((__import_module__("devenv:subprocess/types@0.2.0-draft"), __import_name__("[method]child.stderr")))
extern void __wasm_import_devenv_subprocess_types_method_child_stderr(int32_t, uint8_t *);

__attribute__((__import_module__("devenv:subprocess/types@0.2.0-draft"), __import_name__("[method]child.subscribe")))
extern int32_t __wasm_import_devenv_subprocess_types_method_child_subscribe(int32_t);

__attribute__((__import_module__("devenv:subprocess/types@0.2.0-draft"), __import_name__("[method]child.exit-status")))
extern void __wasm_import_devenv_subprocess_types_method_child_exit_status(int32_t, uint8_t *);

__attribute__((__import_module__("devenv:subprocess/types@0.2.0-draft"), __import_name__("[method]child.terminate")))
extern void __wasm_import_devenv_subprocess_types_method_child_terminate(int32_t);

// Imported Functions from `devenv:subprocess/host@0.2.0-draft`

__attribute__((__import_module__("devenv:subprocess/host@0.2.0-draft"), __import_name__("spawn")))
extern void __wasm_import_devenv_subprocess_host_spawn(uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint8_t *);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("wasi:io/error@0.2.0"), __import_name__("[resource-drop]error")))
extern void __wasm_import_io_error_error_drop(int32_t handle);

void io_error_error_drop_own(io_error_own_error_t handle) {
  __wasm_import_io_error_error_drop(handle.__handle);
}

io_error_borrow_error_t io_error_borrow_error(io_error_own_error_t arg) {
  return (io_error_borrow_error_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("[resource-drop]pollable")))
extern void __wasm_import_poll_pollable_drop(int32_t handle);

void poll_pollable_drop_own(poll_own_pollable_t handle) {
  __wasm_import_poll_pollable_drop(handle.__handle);
}

poll_borrow_pollable_t poll_borrow_pollable(poll_own_pollable_t arg) {
  return (poll_borrow_pollable_t) { arg.__handle };
}

void poll_list_borrow_pollable_free(poll_list_borrow_pollable_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    poll_borrow_pollable_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void subprocess_host_list_u32_free(subprocess_host_list_u32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void streams_stream_error_free(streams_stream_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
  }
}

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[resource-drop]input-stream")))
extern void __wasm_import_streams_input_stream_drop(int32_t handle);

void streams_input_stream_drop_own(streams_own_input_stream_t handle) {
  __wasm_import_streams_input_stream_drop(handle.__handle);
}

streams_borrow_input_stream_t streams_borrow_input_stream(streams_own_input_stream_t arg) {
  return (streams_borrow_input_stream_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[resource-drop]output-stream")))
extern void __wasm_import_streams_output_stream_drop(int32_t handle);

void streams_output_stream_drop_own(streams_own_output_stream_t handle) {
  __wasm_import_streams_output_stream_drop(handle.__handle);
}

streams_borrow_output_stream_t streams_borrow_output_stream(streams_own_output_stream_t arg) {
  return (streams_borrow_output_stream_t) { arg.__handle };
}

void subprocess_host_list_u8_free(subprocess_host_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void streams_result_list_u8_stream_error_free(streams_result_list_u8_stream_error_t *ptr) {
  if (!ptr->is_err) {
    subprocess_host_list_u8_free(&ptr->val.ok);
  } else {
    streams_stream_error_free(&ptr->val.err);
  }
}

void streams_result_u64_stream_error_free(streams_result_u64_stream_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    streams_stream_error_free(&ptr->val.err);
  }
}

void streams_result_void_stream_error_free(streams_result_void_stream_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    streams_stream_error_free(&ptr->val.err);
  }
}

void devenv_subprocess_types_stdin_free(devenv_subprocess_types_stdin_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      break;
    }
  }
}

void devenv_subprocess_types_output_free(devenv_subprocess_types_output_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void subprocess_host_list_string_free(subprocess_host_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    subprocess_host_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      subprocess_host_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void subprocess_host_option_string_free(subprocess_host_option_string_t *ptr) {
  if (ptr->is_some) {
    subprocess_host_string_free(&ptr->val);
  }
}

void subprocess_host_tuple2_string_string_free(subprocess_host_tuple2_string_string_t *ptr) {
  subprocess_host_string_free(&ptr->f0);
  subprocess_host_string_free(&ptr->f1);
}

void subprocess_host_list_tuple2_string_string_free(subprocess_host_list_tuple2_string_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    subprocess_host_tuple2_string_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      subprocess_host_tuple2_string_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void devenv_subprocess_types_option_stdin_free(devenv_subprocess_types_option_stdin_t *ptr) {
  if (ptr->is_some) {
    devenv_subprocess_types_stdin_free(&ptr->val);
  }
}

void devenv_subprocess_types_option_output_free(devenv_subprocess_types_option_output_t *ptr) {
  if (ptr->is_some) {
    devenv_subprocess_types_output_free(&ptr->val);
  }
}

void devenv_subprocess_types_spawn_options_free(devenv_subprocess_types_spawn_options_t *ptr) {
  subprocess_host_string_free(&ptr->command);
  subprocess_host_list_string_free(&ptr->arguments);
  subprocess_host_option_string_free(&ptr->cwd);
  subprocess_host_list_tuple2_string_string_free(&ptr->environment);
  devenv_subprocess_types_option_stdin_free(&ptr->stdin_);
  devenv_subprocess_types_option_output_free(&ptr->stdout_);
  devenv_subprocess_types_option_output_free(&ptr->stderr_);
}

void devenv_subprocess_types_result_void_void_free(devenv_subprocess_types_result_void_void_t *ptr) {
  if (!ptr->is_err) {
  }
}

void devenv_subprocess_types_exit_status_free(devenv_subprocess_types_exit_status_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      devenv_subprocess_types_result_void_void_free(&ptr->val.exited);
      break;
    }
    case 1: {
      break;
    }
  }
}

__attribute__((__import_module__("devenv:subprocess/types@0.2.0-draft"), __import_name__("[resource-drop]child")))
extern void __wasm_import_devenv_subprocess_types_child_drop(int32_t handle);

void devenv_subprocess_types_child_drop_own(devenv_subprocess_types_own_child_t handle) {
  __wasm_import_devenv_subprocess_types_child_drop(handle.__handle);
}

devenv_subprocess_types_borrow_child_t devenv_subprocess_types_borrow_child(devenv_subprocess_types_own_child_t arg) {
  return (devenv_subprocess_types_borrow_child_t) { arg.__handle };
}

void devenv_subprocess_types_option_own_input_stream_free(devenv_subprocess_types_option_own_input_stream_t *ptr) {
  if (ptr->is_some) {
  }
}

void devenv_subprocess_types_option_exit_status_free(devenv_subprocess_types_option_exit_status_t *ptr) {
  if (ptr->is_some) {
    devenv_subprocess_types_exit_status_free(&ptr->val);
  }
}

void devenv_subprocess_host_spawn_options_free(devenv_subprocess_host_spawn_options_t *ptr) {
  devenv_subprocess_types_spawn_options_free(ptr);
}

void devenv_subprocess_host_result_own_child_string_free(devenv_subprocess_host_result_own_child_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    subprocess_host_string_free(&ptr->val.err);
  }
}

void subprocess_host_string_set(subprocess_host_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void subprocess_host_string_dup(subprocess_host_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void subprocess_host_string_dup_n(subprocess_host_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void subprocess_host_string_free(subprocess_host_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void io_error_method_error_to_debug_string(io_error_borrow_error_t self, subprocess_host_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_io_error_method_error_to_debug_string((self).__handle, ptr);
  *ret = (subprocess_host_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

bool poll_method_pollable_ready(poll_borrow_pollable_t self) {
  int32_t ret = __wasm_import_poll_method_pollable_ready((self).__handle);
  return ret;
}

void poll_method_pollable_block(poll_borrow_pollable_t self) {
  __wasm_import_poll_method_pollable_block((self).__handle);
}

void poll_poll(poll_list_borrow_pollable_t *in, subprocess_host_list_u32_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_poll_poll((uint8_t *) (*in).ptr, (*in).len, ptr);
  *ret = (subprocess_host_list_u32_t) { (uint32_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

bool streams_method_input_stream_read(streams_borrow_input_stream_t self, uint64_t len, subprocess_host_list_u8_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_input_stream_read((self).__handle, (int64_t) (len), ptr);
  streams_result_list_u8_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (subprocess_host_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + (4+1*sizeof(void*)))) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_input_stream_blocking_read(streams_borrow_input_stream_t self, uint64_t len, subprocess_host_list_u8_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_input_stream_blocking_read((self).__handle, (int64_t) (len), ptr);
  streams_result_list_u8_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (subprocess_host_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + (4+1*sizeof(void*)))) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_input_stream_skip(streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_input_stream_skip((self).__handle, (int64_t) (len), ptr);
  streams_result_u64_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 8));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_input_stream_blocking_skip(streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_input_stream_blocking_skip((self).__handle, (int64_t) (len), ptr);
  streams_result_u64_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 8));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

streams_own_pollable_t streams_method_input_stream_subscribe(streams_borrow_input_stream_t self) {
  int32_t ret = __wasm_import_streams_method_input_stream_subscribe((self).__handle);
  return (streams_own_pollable_t) { ret };
}

bool streams_method_output_stream_check_write(streams_borrow_output_stream_t self, uint64_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_check_write((self).__handle, ptr);
  streams_result_u64_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 8));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_write(streams_borrow_output_stream_t self, subprocess_host_list_u8_t *contents, streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_write((self).__handle, (uint8_t *) (*contents).ptr, (*contents).len, ptr);
  streams_result_void_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_blocking_write_and_flush(streams_borrow_output_stream_t self, subprocess_host_list_u8_t *contents, streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_blocking_write_and_flush((self).__handle, (uint8_t *) (*contents).ptr, (*contents).len, ptr);
  streams_result_void_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_flush(streams_borrow_output_stream_t self, streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_flush((self).__handle, ptr);
  streams_result_void_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_blocking_flush(streams_borrow_output_stream_t self, streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_blocking_flush((self).__handle, ptr);
  streams_result_void_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

streams_own_pollable_t streams_method_output_stream_subscribe(streams_borrow_output_stream_t self) {
  int32_t ret = __wasm_import_streams_method_output_stream_subscribe((self).__handle);
  return (streams_own_pollable_t) { ret };
}

bool streams_method_output_stream_write_zeroes(streams_borrow_output_stream_t self, uint64_t len, streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_write_zeroes((self).__handle, (int64_t) (len), ptr);
  streams_result_void_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_blocking_write_zeroes_and_flush(streams_borrow_output_stream_t self, uint64_t len, streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_blocking_write_zeroes_and_flush((self).__handle, (int64_t) (len), ptr);
  streams_result_void_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_splice(streams_borrow_output_stream_t self, streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_splice((self).__handle, (src).__handle, (int64_t) (len), ptr);
  streams_result_u64_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 8));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool streams_method_output_stream_blocking_splice(streams_borrow_output_stream_t self, streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_streams_method_output_stream_blocking_splice((self).__handle, (src).__handle, (int64_t) (len), ptr);
  streams_result_u64_stream_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      streams_stream_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 8));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool devenv_subprocess_types_method_child_stdout(devenv_subprocess_types_borrow_child_t self, devenv_subprocess_types_own_input_stream_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_devenv_subprocess_types_method_child_stdout((self).__handle, ptr);
  devenv_subprocess_types_option_own_input_stream_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (devenv_subprocess_types_own_input_stream_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

bool devenv_subprocess_types_method_child_stderr(devenv_subprocess_types_borrow_child_t self, devenv_subprocess_types_own_input_stream_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_devenv_subprocess_types_method_child_stderr((self).__handle, ptr);
  devenv_subprocess_types_option_own_input_stream_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (devenv_subprocess_types_own_input_stream_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

devenv_subprocess_types_own_pollable_t devenv_subprocess_types_method_child_subscribe(devenv_subprocess_types_borrow_child_t self) {
  int32_t ret = __wasm_import_devenv_subprocess_types_method_child_subscribe((self).__handle);
  return (devenv_subprocess_types_own_pollable_t) { ret };
}

bool devenv_subprocess_types_method_child_exit_status(devenv_subprocess_types_borrow_child_t self, devenv_subprocess_types_exit_status_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[3];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_devenv_subprocess_types_method_child_exit_status((self).__handle, ptr);
  devenv_subprocess_types_option_exit_status_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      devenv_subprocess_types_exit_status_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 1));
      switch ((int32_t) variant.tag) {
        case 0: {
          devenv_subprocess_types_result_void_void_t result;
          switch ((int32_t) *((uint8_t*) (ptr + 2))) {
            case 0: {
              result.is_err = false;
              break;
            }
            case 1: {
              result.is_err = true;
              break;
            }
          }
          variant.val.exited = result;
          break;
        }
        case 1: {
          variant.val.exited_with_code = (uint8_t) ((int32_t) *((uint8_t*) (ptr + 2)));
          break;
        }
        case 2: {
          break;
        }
      }

      option.val = variant;
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

void devenv_subprocess_types_method_child_terminate(devenv_subprocess_types_borrow_child_t self) {
  __wasm_import_devenv_subprocess_types_method_child_terminate((self).__handle);
}

bool devenv_subprocess_host_spawn(devenv_subprocess_host_spawn_options_t *options, devenv_subprocess_host_own_child_t *ret, subprocess_host_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if (((*options).cwd).is_some) {
    const subprocess_host_string_t *payload0 = &((*options).cwd).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  int32_t option9;
  int32_t option10;
  int32_t option11;
  if (((*options).stdin_).is_some) {
    const devenv_subprocess_types_stdin_t *payload4 = &((*options).stdin_).val;
    int32_t variant;
    int32_t variant8;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        variant = 0;
        variant8 = 0;
        break;
      }
      case 1: {
        variant = 1;
        variant8 = 0;
        break;
      }
      case 2: {
        const devenv_subprocess_types_own_input_stream_t *payload7 = &(*payload4).val.pipe;
        variant = 2;
        variant8 = (*payload7).__handle;
        break;
      }
    }
    option9 = 1;
    option10 = variant;
    option11 = variant8;
  } else {
    option9 = 0;
    option10 = 0;
    option11 = 0;
  }
  int32_t option18;
  int32_t option19;
  if (((*options).stdout_).is_some) {
    const devenv_subprocess_types_output_t *payload13 = &((*options).stdout_).val;
    int32_t variant17;
    switch ((int32_t) (*payload13).tag) {
      case 0: {
        variant17 = 0;
        break;
      }
      case 1: {
        variant17 = 1;
        break;
      }
      case 2: {
        variant17 = 2;
        break;
      }
    }
    option18 = 1;
    option19 = variant17;
  } else {
    option18 = 0;
    option19 = 0;
  }
  int32_t option26;
  int32_t option27;
  if (((*options).stderr_).is_some) {
    const devenv_subprocess_types_output_t *payload21 = &((*options).stderr_).val;
    int32_t variant25;
    switch ((int32_t) (*payload21).tag) {
      case 0: {
        variant25 = 0;
        break;
      }
      case 1: {
        variant25 = 1;
        break;
      }
      case 2: {
        variant25 = 2;
        break;
      }
    }
    option26 = 1;
    option27 = variant25;
  } else {
    option26 = 0;
    option27 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_devenv_subprocess_host_spawn((uint8_t *) ((*options).command).ptr, ((*options).command).len, (uint8_t *) ((*options).arguments).ptr, ((*options).arguments).len, option, option1, option2, (uint8_t *) ((*options).environment).ptr, ((*options).environment).len, option9, option10, option11, option18, option19, option26, option27, ptr);
  devenv_subprocess_host_result_own_child_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (devenv_subprocess_host_own_child_t) { *((int32_t*) (ptr + sizeof(void*))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (subprocess_host_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_subprocess_host(void);
__attribute__((used))
void __component_type_object_force_link_subprocess_host_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_subprocess_host();
}
